# name of the pipeline 
name: Terraform deployment to AWS for Benco Republic

# Work on workflow trigger 
on:
  push:
    branches:
      - main
  workflow_dispatch:

  # job section 

jobs:
    terraform-deployment:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.6.6
            cli_config_credentials: true
            cli_config_credentials_config: |
              credentials "app.terraform.io" {
                token = "${{ secrets.TERRAFORM_TOKEN }}"
              }

        - name: Terraform Init
          run: terraform init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

        # - name: Terraform Plan
        #   run: terraform plan

        # - name: Terraform Apply
        #   run: terraform apply -auto-approve

